### ISSUE TITLE
rltools is missing

### ISSUE THREAD

**Issue by emanuelepesce** [sisl/MADRL#13]
> ModuleNotFoundError: No module named 'rltools'

Line 1: MADRL/madrl_environments/__init__.py

> from rltools.util import EzPickle, stack_dict_list

It doesn't work and I didn't find this module here.

**Comment by rejuvyesh** [comment]
You forgot using `git clone --recursive` when cloning.

**Comment by chauncyzhu** [comment]
besides that, you can find rltools in this link

> https://github.com/sisl/rltools
