### ISSUE TITLE
model monitoring

### ISSUE THREAD

**Issue by dwijr** [sisl/MADRL#17]
thank you for your codes
I can't install monitoring model which is  in madrl environment.
the error:
pip install gym monitoring
Requirement already satisfied: gym in ./anaconda3/lib/python3.6/site-packages (0.10.9)
Collecting monitoring
  Using cached https://files.pythonhosted.org/packages/a8/db/e8118fe34d232da4834ef49fe9a191a933911968e6e795936fc490920e09/monitoring-0.9.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w2/yh_z8t9d09qbs732pclkqh8m0000gn/T/pip-install-ll5v0fgh/monitoring/setup.py", line 5, in <module>
        VERSION = eval(filter(lambda _:_.startswith("__version__"), file("Sources/monitoring/__init__.py").readlines())[0].split("=")[1])
    NameError: name 'file' is not defined

**Comment by rejuvyesh** [comment]
This codebase uses a very old version of gym, which included the monitoring file as well.
