### ISSUE TITLE
DQN

### ISSUE THREAD

**Issue by colinsb** [sisl/MADRL#19]
I noticed that your paper has graphs produced from average DQN rewards, but it seems to me that something is not working correctly with your DQN algorithm. Also, when I try to apply the algorithm to the pursuit environment, there is a problem with the rank of your tensors being to low. I also see #TODO for the pursuit action spaces. Are there any missing commits or any directions you can point me in to get DQN from rltools running on the pursuit environment?

**Comment by rejuvyesh** [comment]
Resolved via email.

**Comment by Amanda-1997** [comment]
Hi, could you please tell me how to run the multi-agent env `pursuit ` using DQN?
I obtain the agents' joint action, but I can't use the operator `step`
