### ISSUE TITLE
rltools is missing

### ISSUE THREAD

**Issue by maxhuettenrauch** [sisl/MADRL#2]
Hi

I just tried to clone the repository but it seems that rltools is gone. Do you know where I can still find it or can you reupload it?

Thanks

**Comment by rejuvyesh** [comment]
It should be available now: https://github.com/sisl/rltools

It's not necessary though. A few `try` blocks should fix the dependencies.

**Comment by etotheipluspi** [comment]
Just to clarify, rltools has a TRPO implementation that can be used for running experiment. If you want to just use rllab for the algorithmic backend, you don't need rltools.
