### ISSUE TITLE
decrollout missing from rllab sampler

### ISSUE THREAD

**Issue by varunjammula** [sisl/MADRL#20]
`from rllab.sampler.utils import rollout, decrollout 
`
The decrollout function is missing from the rllab branch sub module. Where can I find the function definition?

**Comment by rejuvyesh** [comment]
This one? 
https://github.com/rejuvyesh/rllab/blob/jkg/ma/rllab/sampler/utils.py#L40

**Comment by varunjammula** [comment]
Thank you so much, I used the master branch and could not find it.
