### ISSUE TITLE
Get Action Policy Pursuit

### ISSUE THREAD

**Issue by DjedjigaBHJ** [sisl/MADRL#24]
I'm trying to display the  agent's actions  using these lines: 
```
act_fns = [lambda o: policy.get_action(o)[0]] * len(self.env.agents)
print(act_fcs)
```
but i get that " [<function RLLabRunner.__call__.<locals>.<lambda> at 0x7fb68ce15400>, <function RLLabRunner.__call__.<locals>.<lambda> at 0x7fb68ce15400>]"
when executing !!
Do i miss something ?

**Comment by rejuvyesh** [comment]
These are only the action functions. You need to pass them an observation to get any actions.

**Comment by DjedjigaBHJ** [comment]
Thanks,
I wanted to get the action list taken at every iteration, and for that i'm, now, using the "step" function of the environment script. It takes the list of the agent's action as input.
