### ISSUE TITLE
multi_ant.py#L138

### ISSUE THREAD

**Issue by GoingMyWay** [sisl/MADRL#26]
https://github.com/sisl/MADRL/blob/a3651e225c388c8eb42142a4764fb3f080f07def/madrl_environments/mujoco/ant/multi_ant.py#L138

I think it is not self.mode.data, it is self.data

**Comment by rejuvyesh** [comment]
It's an old version of MuJoCo. Things used to be different back then?

**Comment by GoingMyWay** [comment]
> It's an old version of MuJoCo. Things used to be different back then?

I later I can get `self.model.data` with `self.sim.data` by

        self.sim = MjSim(self.model)
        self.data = self.sim.data

I think `multi-ant` is not a real mutil-agent scenario to some extent since the agent is the leg of the ant. I thought this scenario would spawn many ants and work cooperatively to accomplish some taks.  So, in my view, it is strange. I was considering using it in my paper. But I do not think the paper reviewers will but this scenario.

Anyway, thanks for this repo.

**Comment by rejuvyesh** [comment]
Yeah, this particular scenario was with each leg of the ant being a separate agent and not multiple ants. MultiWalker might be more like what you want?

**Comment by GoingMyWay** [comment]
> Yeah, this particular scenario was with each leg of the ant being a separate agent and not multiple ants. MultiWalker might be more like what you want?

MultiWalker is a better choice for me.
