### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by justinkterry** [sisl/MADRL#29]
Hey, I'm working with the environments from this library, and have forked them to make some changes and would like to rerelease them as part of the supplemental materials of my paper. For that to be fully legal, this code would have to be released under an open source license (currently it's under no license). An MIT license is the simplest and easiest to work with in terms of others reusing your code. Could you please add that to this library real quick to make the university IP lawyer happy?

**Comment by rejuvyesh** [comment]
Fixed with c785a74a2f8c75acf1b4d57ee07aa02c807c125e.

**Comment by rejuvyesh** [comment]
Would love to know what you did with this!
