### ISSUE TITLE
modul not found

### ISSUE THREAD

**Issue by mahmoodsafavi** [sisl/MADRL#6]
hi 
i have following  error message when run run_multiwalker.py code.
"Traceback (most recent call last):
  File "runners/run_multiwalker.py", line 7, in <module>
    from runners import RunnerParser
ModuleNotFoundError: No module named 'runners' "

**Comment by rejuvyesh** [comment]
Did you update your `PYTHONPATH` as suggested in the README?

**Comment by mahmoodsafavi** [comment]
yes, i run this:
export PYTHONPATH=$(pwd):$(pwd)/rltools:$(pwd)/rllab:$PYTHONPATH

**Comment by rejuvyesh** [comment]
In the terminal where you run the command, what's the output of `echo $PYTHONPATH`? Also what's the `python` version?

**Comment by mahmoodsafavi** [comment]
command1: echo $PYTHONPATH return 
/home/mahmood:/home/mahmood/rltools:/home/mahmood/rllab:
command2: python --version return Python 2.7.12+
command3:python3 --version return 3.5.2+

**Comment by mahmoodsafavi** [comment]
please help me :(

**Comment by rejuvyesh** [comment]
You have to re-export `PYTHONPATH` every time you open a new terminal. And use `python3` to run any commands.

**Comment by mahmoodsafavi** [comment]
thank you for replay.
i'm new in python, :-(
how can run BWT ???
