### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by mahmoodsafavi** [sisl/MADRL#7]
is there user interface implementation in pursuit evader problem?
in other word UI show me movements of agents. 
if yes,how can use it?

**Comment by etotheipluspi** [comment]
Yep, there is. After you initialize any of the environemnts, you can call the render function like so:

```python
env = PursuitEvade([TwoDMaps.rectangle_map(10, 10)])
env.render() # renders the env
```
The interface is similar to that of OpenAI gym.

**Comment by nanxintin** [comment]
Hi, I have followed your answer, and add the "env.render()" after "env = PursuitEvade()" in the run_pursuit.py file.
However, when I start the training with " python runners/run_pursuit.py rltools", there is just a picture of the  pursuit, unlike the moving agent in the gym.
How can I visualize the agents' moving when training?
